apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis-green
  name: redis-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-green
  template:
    metadata:
      labels:
        app: redis-green
    spec:
      containers:
      - image: redis:alpine
        name: redis-green
        ports:
        - containerPort: 6379
          name: redis-green
        volumeMounts:
        - mountPath: /data
          name: redis-data
      volumes:
      - name: redis-data
        emptyDir: {} 
      tolerations:
       - key: "environment"
         operator: "Equal"
         value: "green"
         effect: "NoSchedule"
      affinity:
        nodeAffinity:
         requiredDuringSchedulingIgnoredDuringExecution:
           nodeSelectorTerms:
            - matchExpressions: 
               - key: environment
                 operator: In
                 values:
                    - green
      resources:
          requests:
            cpu: "100m"      # 0.05 cores
            memory: "128Mi"
          limits:
            cpu: "200m"     # 0.1 cores
            memory: "256Mi"              
