apiVersion: v2
name: vote-app
description: A helm chart for vote-app
type: application

# This is the chart version. Update this when you change the templates.
version: 1.0.0

# This is the version of the app (e.g., your image tag).
appVersion: "1.0.0"

maintainers:
  - name: ranjanabha bhattacharya
    email: ranjanabha@gmail.com

# Restrict to modern Kubernetes versions
kubeVersion: ">=1.25.0-0"