apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote-green
    environment: green
  name: vote-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-green
      environment: green
  template:
    metadata:
      labels:
        app: vote-green
        environment: green
    spec:
      containers:
      - image: azureciregistry.azurecr.io/votingapp/vote:57
        name: vote-green
        ports:
        - containerPort: 80
          name: vote
        envFrom:
          - configMapRef:
              name: vote-config        
      tolerations:
      - key: "environment"
        operator: "Equal"
        value: "green"
        effect: "NoSchedule"
      affinity:
       nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
         nodeSelectorTerms:
         - matchExpressions:
           - key: environment
             operator: In
             values: 
              - green
      resources:
          requests:
            cpu: "100m"      # 0.05 cores
            memory: "128Mi"
          limits:
            cpu: "200m"     # 0.1 cores
            memory: "256Mi"         
